name: shop_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  equatable: ^2.0.5
  dio: ^4.0.6
  dartz: ^0.10.1
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  carousel_slider: ^4.1.1
  bottom_navy_bar: ^6.0.0
  flutter_carousel_slider: ^1.0.8
  flutter_staggered_grid_view: ^0.6.2
  shared_preferences: ^2.0.15
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.1
  geolocator: ^9.0.2
  material_floating_search_bar: ^0.3.7
  flutter_screenutil: ^5.6.0
  smooth_page_indicator: ^1.0.0+2
  uuid: ^3.0.7
  flutter_svg: ^1.1.6
  flutter_launcher_icons_maker: "^0.10.1"









dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  web: true
  image_path: "assets/images/app_icon.jpg"


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/



  fonts:
    - family: customFont1
      fonts:
       - asset: assets/fonts/RubikBeastly-Regular.ttf
         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
